import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Sidebar configuration for Harness docs (v1.35.0).
 * Top-level order: Getting Started → Configuration → API → Architecture → Installation → Migration → Project → FAQ
 * Only includes pages that actually exist.
 * API sidebar is auto-generated by docusaurus-plugin-openapi-docs.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: '🚀 Getting Started',
      collapsed: false,
      items: [
        'tutorials/quickstart',
        'tutorials/first-agent',
        'tutorials/plugin-development',
      ],
    },
    {
      type: 'category',
      label: '⚙️ Configuration',
      collapsed: false,
      items: [
        'configuration/config-overview',
        'configuration/api-authentication',
        'configuration/reference',
        'configuration/api-config-map',
      ],
    },
    {
      type: 'category',
      label: '🔌 API Reference',
      collapsed: false,
      items: [
        'api/overview',
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
    {
      type: 'category',
      label: '🏗️ Architecture',
      collapsed: false,
      items: [
        'architecture/overview',
      ],
    },
    {
      type: 'category',
      label: '📦 Installation',
      collapsed: false,
      items: [
        'installation/install-linux',
        'installation/install-macos',
        'installation/install-windows',
        'installation/install-docker',
        'installation/install-kubernetes',
        'installation/install-from-source',
      ],
    },
    {
      type: 'category',
      label: '🔄 Migration',
      collapsed: true,
      items: [
        'migration/migration-v132-to-v140',
      ],
    },
    {
      type: 'category',
      label: '💼 Use Cases',
      collapsed: true,
      items: [
        'use-cases/overview',
      ],
    },
    {
      type: 'category',
      label: '🗺️ Project',
      collapsed: true,
      items: [
        'project/roadmap',
      ],
    },
    {
      type: 'category',
      label: '❓ FAQ',
      collapsed: true,
      items: [
        'faq/general',
      ],
    },
    {
      type: 'category',
      label: '🛠️ Troubleshooting',
      collapsed: true,
      link: { type: 'generated-index', description: 'Common issues and solutions' },
      items: [],
    },
  ],
};

export default sidebars;
