import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Sidebar configuration for Harness docs.
 * Only includes pages that actually exist.
 * API sidebar is auto-generated by docusaurus-plugin-openapi-docs.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'tutorials/quickstart',
        'tutorials/first-agent',
        'tutorials/plugin-development',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      collapsed: true,
      items: [
        'architecture/overview',
      ],
    },
    {
      type: 'category',
      label: 'Configuration',
      items: [
        'configuration/config-overview',
        'configuration/api-authentication',
        'configuration/reference',
        'configuration/api-config-map',
      ],
    },
    {
      type: 'category',
      label: 'Installation',
      items: [
        'installation/install-linux',
        'installation/install-macos',
        'installation/install-windows',
        'installation/install-docker',
        'installation/install-kubernetes',
        'installation/install-from-source',
      ],
    },
    {
      type: 'category',
      label: 'Migration',
      collapsed: true,
      items: [
        'migration/migration-v132-to-v140',
      ],
    },
    {
      type: 'category',
      label: 'Use Cases',
      collapsed: true,
      items: [
        'use-cases/overview',
      ],
    },
    {
      type: 'category',
      label: 'Project',
      collapsed: true,
      items: [
        'project/roadmap',
      ],
    },
    {
      type: 'category',
      label: 'API',
      collapsed: true,
      items: [
        'api/overview',
      ],
    },
    {
      type: 'category',
      label: 'FAQ',
      collapsed: true,
      items: [
        'faq/general',
      ],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      collapsed: true,
      link: { type: 'generated-index', description: 'Common issues and solutions' },
      items: [],
    },
  ],
};

export default sidebars;
